### ISSUE TITLE
Blank dashboards with only logout link

### ISSUE THREAD

**Issue by psych0d0g** [sipcapture/homer-api#1]
fresh installation, i cant get the dashboards to display,
nginx tells me the following on every dashboard / link:

2015/06/03 14:24:21 [error] 3805#0: _84 FastCGI sent in stderr: "PHP message: PHP Notice:  Undefined variable: parameters in /var/www/api/RestService/Client.php on line 180
PHP message: PHP Warning:  preg_match(): Compilation failed: unmatched parentheses at offset 8 in /var/www/api/RestService/Server.php on line 1198
PHP message: PHP Notice:  Undefined property: RestAPI\Dashboard::$authmodule in /var/www/api/RestApi/Dashboard.php on line 50
PHP message: PHP Notice:  Undefined property: RestAPI\Dashboard::$_instance in /var/www/api/RestApi/Dashboard.php on line 368" while reading response header from upstream, client: *__._**.**_._**, server: "blacked-out", request: "GET /api/dashboard/store/search HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "blacked-out"

Debian Wheezy
nginx 1.2.1
php5-fpm 5.4.39
mysql-server: 5.5.43

**Comment by adubovikov** [comment]
but you can log in ?

**Comment by adubovikov** [comment]
did you create configure.php and preferences.php as well ?

**Comment by psych0d0g** [comment]
yes and yes i can login, ive imported the sql statements, ran the perl script all without problems, just the dashboard frame is staying empty for me

**Comment by adubovikov** [comment]
can you ping me in gtalk ?

**Comment by psych0d0g** [comment]
dont have you'r gtalk i think

**Comment by psych0d0g** [comment]
got it i guess, ping'd you in hangouts

**Comment by adubovikov** [comment]
pinged back

**Comment by adubovikov** [comment]
ok, fixed
