### ISSUE TITLE
issue api/v1/search/method with multi-node

### ISSUE THREAD

**Issue by Mickaelh51** [sipcapture/homer-api#104]
Hi,
I have a issue (maybe with multi-node) when I want to see any methods.

![screenshot-homerdev 2016-09-05 11-59-19](https://cloud.githubusercontent.com/assets/9885404/18244535/cfef8b62-7360-11e6-91c3-c07f1a5a3582.png)

With the firefox console, I can see no node param sent to the api.

![json_post](https://cloud.githubusercontent.com/assets/9885404/18244689/b430fa86-7361-11e6-8729-c31b7f4091c6.jpg)

PS: these screenshots are differents (not the same call-id).

Can you help me with this issue, I can't find where it is.

thanks in advance

**Comment by adubovikov** [comment]
the issue is because you didn't send the location node. But I think we have fixed it already. Do you use the last git ?

**Comment by Mickaelh51** [comment]
Yes I'm using the last git:
Homer-ui: 

```
commit 6a5b99f23be52ba04ba206ec4a8b005712927e1e
Merge: fdbc9bf 8f03ff7
Author: Alexandr Dubovikov <alexandr.dubovikov@gmail.com>
Date:   Tue Aug 23 20:53:59 2016 +0200

    Merge pull request #80 from negbie/master

    Extend X-RTP-Stat header information

```

Homer API:

```
commit bbb6ad8a2bef8283ad5284a9741d61920dd57678
Merge: 502c547 04a1878
Author: Alexandr Dubovikov <alexandr.dubovikov@gmail.com>
Date:   Tue Aug 23 20:53:14 2016 +0200

    Merge pull request #99 from negbie/master

    Extend X-RTP-Stat header information
```

I'm sorry, but I don't know where location->node object should be populated...

**Comment by adubovikov** [comment]
can you please check the result of /api/v1/search/transaction ? What do you have in calldata->dbnode ?

**Comment by adubovikov** [comment]
btw, your Homer-API is outdate
as I wrote the issue has to be fixed already! Please update to the last one!

**Comment by Mickaelh51** [comment]
pfff I'm so noob sorry !
it's ok for me.

**Comment by adubovikov** [comment]
np, please close the ticket :-)
