### ISSUE TITLE
use different syslog tag name for Kamailio process

### ISSUE THREAD

**Issue by dpocock** [sipcapture/homer-api#106]
I've suggested a new cfg parameter in Kamailio to make the tag name configurable:

https://github.com/kamailio/kamailio/issues/780

After that is done, please consider adding `log_tag` to the example cfg files.

**Comment by miconda** [comment]
Kamailio has an exiting parameter that allows setting the syslog application name, respectively **log_name**:
- https://www.kamailio.org/wiki/cookbooks/4.4.x/core#log_name

**Comment by adubovikov** [comment]
https://github.com/sipcapture/homer-api/commit/332e96e8933b1018335a529c1a6eeba6f0d09c2b

added
