### ISSUE TITLE
update log rotation sample

### ISSUE THREAD

**Issue by dpocock** [sipcapture/homer-api#107]
The log rotation config here:
https://github.com/sipcapture/homer-api/blob/master/examples/sipcapture/sipcapture.logrotated

relies on a PID file.  It probably doesn't exist at that location in most systems.

Most modern logrotate configs use invoke-rc.d, here is an example:
https://anonscm.debian.org/cgit/collab-maint/rsyslog.git/tree/debian/rsyslog.logrotate

**Comment by adubovikov** [comment]
https://github.com/sipcapture/homer-api/commit/40730037a8157ab0e57121f17561a6d92d0d4ef9

done
