### ISSUE TITLE
PostgreSQL schema setup doesn't grant access

### ISSUE THREAD

**Issue by dpocock** [sipcapture/homer-api#108]
The UI wasn't working and I saw the error `permission denied for relation user_menu` in Apache `error.log`

I needed to log in to each database and run the command:

```
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public  TO homer_user;
```

Maybe this (or a more fine tuned set of permissions) needs to be specified at the bottom of each schema_*.sql file for PostgreSQL

**Comment by adubovikov** [comment]
done
https://github.com/sipcapture/homer-api/commit/f55c8fc3367f6e764fb618566ad3aced8da36d18
https://github.com/sipcapture/homer-api/commit/ade8274d6856066ef89d0fb529918a5b66b6666b
https://github.com/sipcapture/homer-api/commit/0a23a3fa23bad1f103192aa0f3e492daa309fe3c
