### ISSUE TITLE
PostgreSQL grant homer_data sequences

### ISSUE THREAD

**Issue by dpocock** [sipcapture/homer-api#110]
I needed to do this in the homer_data schema, otherwise Kamailio couldn't insert anything:

```
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public  TO homer_user;
```

**Comment by adubovikov** [comment]
https://github.com/sipcapture/homer-api/commit/2f4ac8d59290b58a3d81078900182e781ffac477

done
