### ISSUE TITLE
PostgreSQL has no DIV operator

### ISSUE THREAD

**Issue by dpocock** [sipcapture/homer-api#111]
`preferences.php` contains

```
define('FIELDS_CAPTURE', "id, date, (micro_ts DIV 1000)  .......
```

For PostgreSQL, it needs to use `/` instead of `DIV`, e.g.

```
define('FIELDS_CAPTURE', "id, date, (micro_ts / 1000)  .......
```

**Comment by adubovikov** [comment]
the problem "/" return float vs int .... need find the best way

**Comment by adubovikov** [comment]
does it work for pgsql ?

floor(micro_ts/1000) as milli_ts ?

**Comment by dpocock** [comment]
yes, the expression with `floor` appears to work on PostgreSQL

**Comment by adubovikov** [comment]
https://github.com/sipcapture/homer-api/commit/0cbde23b6040e4be3a84d36c394cef61a742e5c3

done
