### ISSUE TITLE
can't search with PostgreSQL

### ISSUE THREAD

**Issue by dpocock** [sipcapture/homer-api#115]
With the latest code from Git, when I try to search from the web UI I see these errors in Apache `error.log`

```
INSERT INTO setting SET uid='1', param_name='search', param_value = '{}'], referer: 
Array\n(\n    [0] => 42601\n    [1] => 7\n    [2] => ERROR:  syntax error at or near "SET"\nLINE 1: INSERT INTO setting SET uid='1', param_name='search', param_...\n                            ^\n)\n, 
```

**Comment by adubovikov** [comment]
can you please provide full query ?

**Comment by dpocock** [comment]
The full query is there on the first line, it is:

```
INSERT INTO setting SET uid='1', param_name='search', param_value = '{}'
```

**Comment by adubovikov** [comment]
https://github.com/sipcapture/homer-api/commit/e6cf13b752f85de043b7d708445dfb52620a65b5
https://github.com/sipcapture/homer-api/commit/e3d11be79c1d4ca891aeacb1e1b5d73a17cbea95
