### ISSUE TITLE
misleading username/password errors

### ISSUE THREAD

**Issue by dpocock** [sipcapture/homer-api#116]
The error `Email and password combination not recognised` appears for many issues that are not account related.

For example:
- wrong database credentials or port number in configuration.php
- failing to specify correct database type in preferences.php

Furthermore, in many of these cases the real reason for the error is not logged anywhere and can only be discovered by opening the Network console in the browser and manually looking at the HTTP response text.

Suggestions:
- only give the Email/password error if it really is a user account issue
- for any other issue, give an error such as "Your system is not configured correctly, please check server logs"
- for any database connection issue, log something to the Apache error.log file

**Comment by adubovikov** [comment]
http://install.sipcapture.io/
