### ISSUE TITLE
database settings split across configuration.php and preference.php

### ISSUE THREAD

**Issue by dpocock** [sipcapture/homer-api#117]
DATABASE_DRIVER is in preference.php but the other settings are in configuration.php

Could you combine all these settings in one place, probably configuration.php?

**Comment by adubovikov** [comment]
@dpocock

configuration.php has only "local settings" that will be never change: username, password, path etc
therefore we have split settings to the two files.

**Comment by dpocock** [comment]
I'm not suggesting to combine all the settings, only the settings related to databases

preferences.php has DATABASE_DRIVER

configuration.php has username, password, hostname, port, etc

**Comment by adubovikov** [comment]
done
https://github.com/sipcapture/homer-api/commit/1ebd7bf22c7609456960e36ad3cc219e680c4a5e
https://github.com/sipcapture/homer-api/commit/2e80dc6f170fdbdfc203269e507c005a31922eff
