### ISSUE TITLE
api/RestAPI/Admin.php:149-158 does not construct proper insert format for pgsql

### ISSUE THREAD

**Issue by quentusrex** [sipcapture/homer-api#119]
When trying to use the admin panel to create a new user, the function doNewUser does not construct a valid insert statement for pgsql. 

2016/09/20 13:16:16 [error] 16471#0: *281 FastCGI sent in stderr: "PHP message: Fail to execute query: [INSERT INTO "user" SET "password" = crypt('test123', gen_salt('md5')),active = '1', email = 'quentusrex@gmail.com', firstname = 'William', lastname = 'King', grp = 'users,admins', username = 'quentusrex', gid = '10', lastvisit = '2016-09-20 13:16:16']
PHP message: Array
(
    [0] => 42601
    [1] => 7
    [2] => ERROR:  syntax error at or near "SET"
LINE 1: INSERT INTO "user" SET "password" = crypt('test123', gen_sal...
                           ^

Format would need to be:
INSERT INTO films (code, title, did, date_prod, kind)
    VALUES ('T_601', 'Yojimbo', 106, DEFAULT, 'Drama');

with the first ()'s naming the columns, and the second () with the values.

docs here:
https://www.postgresql.org/docs/9.5/static/sql-insert.html

**Comment by adubovikov** [comment]
@quentusrex I will fix ASAP

**Comment by quentusrex** [comment]
I'm running through a full set of tests now on a new install with decent inbound traffic. Likely going to be filing several PRs and/or issues. 

If there are more dealing with admin user management, I'll update/reopen this issue.

**Comment by adubovikov** [comment]
https://github.com/sipcapture/homer-api/commit/64f5fce48498e9edb0ca92d72fad5239664f3495
