### ISSUE TITLE
Feature: Simplify pgsql database creation by reusing the rotate scripts for DB table creation.

### ISSUE THREAD

**Issue by quentusrex** [sipcapture/homer-api#121]
So the pgsql 'fuller' process for creating a new DB could be:
== As postgres admin user ==
1. Create a new table space(for storing the DB in a different path)
2. Create homer_user
3. Create DB with owner as homer_user, and tablespace as created above
== Everything below should be doable with homer_user ==
4. Edit the rotation.ini file for desired DB options(like sip capture column size)
5. Create configuration DB
6. Run the rotate script to create all data, and stats tables.

**Comment by quentusrex** [comment]
For step 3 above, creating the DB with homer_user as the owner will resolve all of the permission issues if the tables, indexes, and sequences would be created by another admin user.

**Comment by adubovikov** [comment]
http://install.sipcapture.io/
