### ISSUE TITLE
rtcp_capture.correlation_id truncated

### ISSUE THREAD

**Issue by dpocock** [sipcapture/homer-api#126]
I notice that values in rtcp_capture.correlation_id appear to be missing the last digit

The column itself is varchar(256) so it doesn't appear to be a schema fault.

**Comment by giavac** [comment]
This should have been fixed already in https://github.com/kamailio/kamailio/commit/6cb0bec7d2491ed3365dc237fc1d8608af246c3a I think.

**Comment by adubovikov** [comment]
it was the issue during RTCP mirroring in Asterisk 1.x. They sent correlation id without \0 and we have garbage at the end. As @giavac already mentioned , we have fixed it because almost everybody migrated to Asterisk 11,12

**Comment by adubovikov** [comment]
the issue has been fixed in kamailio as well
