### ISSUE TITLE
homer_mysql_rotate.pl: redundant parameter, line 157

### ISSUE THREAD

**Issue by gedia** [sipcapture/homer-api#129]
Hello,

I've been getting warnings about a redundant parameter in this script. I'm not familiar with this code or perl, but the attached patch seems to quiet them.

[fix-redundant-arg.txt](https://github.com/sipcapture/homer-api/files/546055/fix-redundant-arg.txt)

**Comment by adubovikov** [comment]
Thank you. Can u please do a pull request?

**Comment by gedia** [comment]
Done. #130

**Comment by adubovikov** [comment]
done. https://github.com/sipcapture/homer-api/commit/37a59fe6852785ee7bccb51729eb46e465ad9f56

you can close the issue :-)

**Comment by gedia** [comment]
I think my previous patch seriously broke the rotation script. I think #132 is the proper solution but please review this more closely. In any case, I strongly believe #130 should be reverted.

**Comment by gedia** [comment]
Reportedly fixed with #132
