### ISSUE TITLE
External Authentication Broken

### ISSUE THREAD

**Issue by blakemckeeby** [sipcapture/homer-api#139]
I believe there is a bug in External Auth that prevents the submitted credentials from being passed to the external system. In Authentication\External::logIn, the $param argument contains the username and password that were submitted by the user. The problem is the $param get’s overwritten on line 62 before the username and password are passed to the remote system.

**Comment by adubovikov** [comment]
this is not auth by "username and password", this is auth by authetication key

https://github.com/sipcapture/homer-api/blob/master/api/Authentication/External.php#L53-L60

but you can add an additional EXTERNAL_AUTH_REQUEST_TYPE == "password" and extend it.

All patches are welcome.

**Comment by adubovikov** [comment]
please reopen if needed
