### ISSUE TITLE
HOMER 5 API missing documentation about QoS reports

### ISSUE THREAD

**Issue by AntonioLatorre** [sipcapture/homer-api#153]
It seems like the API processes correctly requests of QoS reports
However, I can not see any documentation in the apidoc around this function.
Is there any reason why?

**Comment by adubovikov** [comment]
the documentation is as always the last thing that you do. If somebody can help to create a new API DOC it will be very helpful... lets use Swagger for it...

**Comment by lmangani** [comment]
In a perfect world, this would be a Pull-Request :) Please consider doing so if you already found the gap @AntonioLatorre - thanks in advance!

**Comment by adubovikov** [comment]
http://install.sipcapture.io/
