### ISSUE TITLE
Facing issue as Email and password combination not recognised

### ISSUE THREAD

**Issue by sushil246** [sipcapture/homer-api#157]
[Thu May 04 10:23:21.364659 2017] [core:info] [pid 5458] [client 62.25.80.220:37358] AH00128: File does not exist: /var/www/sipcapture/api/v1/session, referer: http://62.25.81.148:8080/
[Thu May 04 10:24:16.648374 2017] [authz_core:debug] [pid 5482] mod_authz_core.c(835): [client 62.25.80.220:37890] AH01628: authorization result: granted (no directives), referer: http://62.25.81.148:8080/
[Thu May 04 10:24:16.648505 2017] [core:info] [pid 5482] [client 62.25.80.220:37890] AH00128: File does not exist: /var/www/sipcapture/api/v1/session, referer: http://62.25.81.148:8080/
[Thu May 04 10:24:25.832210 2017] [authz_core:debug] [pid 5454] mod_authz_core.c(835): [client 62.25.80.220:37974] AH01628: authorization result: granted (no directives), referer: http://62.25.81.148:8080/
[Thu May 04 10:24:25.832336 2017] [core:info] [pid 5454] [client 62.25.80.220:37974] AH00128: File does not exist: /var/www/sipcapture/api/v1/session, referer: http://62.25.81.148:8080/

62.25.80.220 - - [04/May/2017:10:24:16 +0100] "POST /api/v1/session HTTP/1.1" 404 212 "http://62.25.81.148:8080/" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:53.0) Gecko/20100101 Firefox/53.0"
62.25.80.220 - - [04/May/2017:10:24:25 +0100] "POST /api/v1/session HTTP/1.1" 404 212 "http://62.25.81.148:8080/" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:53.0) Gecko/20100101 Firefox/53.0"

httpdconf snippet 
<IfModule !mod_rewrite.c>
LoadModule rewrite_module modules/mod_rewrite.so
</IfModule>

Include conf.modules.d/*.conf
<VirtualHost 62.25.81.148:8080>
        ServerAdmin support@yourhost.org
        ServerName  homer5.yourhost.org

        # Indexes + Directory Root.
        DirectoryIndex index.php index.html index.htm
        DocumentRoot /var/www/sipcapture/

        <Directory /var/www/sipcapture/>
            Options Indexes FollowSymLinks MultiViews
            AllowOverride all
            Order allow,deny
            allow from all
        </Directory>

        # CGI Directory
        ScriptAlias /cgi-bin/ /var/www/sipcapture/cgi-bin/
        <Location "/var/www/sipcapture/cgi-bin">
            Options +ExecCGI -MultiViews
            Order allow,deny
            Allow from all
        </Location>

        # Logfiles
        ErrorLog  /var/log/httpd/sipcapture-error.log
        CustomLog /var/log/httpd/sipcapture-access.log combined
</VirtualHost>

**Comment by lmangani** [comment]
Please reopen if still needed, sorry for missing this
