### ISSUE TITLE
HOMER not showing call data

### ISSUE THREAD

**Issue by chiragd** [sipcapture/homer-api#158]
I have homer install with 74 records for calls today. When I do a count via the sip search page, it tells me I have 74 records.

When I ask it to show me these records I get a blank table.

When I check for other types of records e.g. registrations or options, they show up fine in the table.

The browser console shows me a response from the API which is OK but with the following error:
https://[mydomain]/homer/api/v1/search/data - 200 OK
RESPONSE: SyntaxError: JSON.parse: unexpected end of data at line 1 column 1 of the JSON data.

Any ideas?

Thanks,

C

**Comment by lmangani** [comment]
Please reopen if still an issue, sorry for missing this one.
