### ISSUE TITLE
rtcp_capture table doesn't rotate

### ISSUE THREAD

**Issue by Freenex** [sipcapture/homer-api#159]
Hi,

We have found a little bug in the "homer_mysql_remove_partitions.pl" script. This script tries to rotate rtcp_capture table adding a date suffix, as It doesn't have this suffix it fails. 

We have made a little patch to prevent this script from adding this suffix and It worked in our tests.

Can we help with any pull request or uploading the patch somewhere?

Kind Regards

**Comment by adubovikov** [comment]
Can you please check your rotation.ini script ?

does it looks similar, special in for rtcp_capture ?
https://github.com/sipcapture/homer-api/blob/master/scripts/mysql/rotation.ini

**Comment by adubovikov** [comment]
Thank you for it. Can you please do a pull request ?

**Comment by Freenex** [comment]
I can't create a branch for the pull request. How do I should proceed?

**Comment by lmangani** [comment]
No need for branches, just fork, patch and do a PR to master please.

Thanks!


Kind Regards,

Lorenzo Mangani
*Managing Director and Core Dev*

QXIP BV - Capture Engineering
Amsterdam, The Netherlands

Desk: +31 20 8080468 / +1 202-632-7227
Mobile: +31 6 4603-2730
Email: info@qxip.net

Find our more about HOMER, PCAPTURE, CAPTAGENT and all our Services and
Solutions at http://qxip.net

CONFIDENTIALITY NOTICE: This e-mail message, including any attachments, is
for the sole use of the intended recipient(s) and may contain confidential or
legally privileged information. Any unauthorized review, use, disclosure or
distribution is prohibited. If you are not the intended recipient,
please contact
the sender by reply e-mail and destroy all copies of this original message.

**Comment by Rico29** [comment]
hello,
It does not seem to fix my rtpc_capture table rotation. I've done a fresh install using git as source yesterday, I can see the gommit of Freenex in git log, but my rtcp_capture table still does not rotate.

Regards

**Comment by maltris** [comment]
Hello,

I can confirm that even with the patch, the rtcp_capture-table is not being rotated.

The rtcp_capture_all_<timestamp> tables are properly created and removed, but they are always empty.

Any hints/ideas?

Regards

**Comment by VeselaHouba** [comment]
@maltris Hello, what patch? I can't see any referenced in this issue. 
I've just checked my `rtcp_capture` table, it's not rotating at all.
```
mysql> select id,date from rtcp_capture order by date asc limit 1;
+----+---------------------+
| id | date                |
+----+---------------------+
|  1 | 2019-09-11 04:06:43 |
+----+---------------------+
1 row in set (0.00 sec)
```
I've checked and manually run the rotation script from cron container with debug option (I'm using docker-compose) and it finished successfully, but data in this table are not rotated and it's huuuuuuge.

**Comment by adubovikov** [comment]
http://install.sipcapture.io/
