### ISSUE TITLE
Default rotate script doesn't create old enough tables

### ISSUE THREAD

**Issue by andrewyager** [sipcapture/homer-api#16]
Running a new install of homer5, after executing the default rotate.sh script, the new_tables.pl script hasn't created old enough tables for our kamailio install to be able to insert data. It would appear that this is a timezone related issue (we are in AEST)

**Comment by adubovikov** [comment]
thank you.
fixed.
https://github.com/sipcapture/homer-api/commit/e5c2b0bce98cff98efb71445d4d1c57521273ae3
