### ISSUE TITLE
Using RDBMS Partitioning System instead of external Script 

### ISSUE THREAD

**Issue by isaiasanchez** [sipcapture/homer-api#164]
I would like to disable Homer partition rotation to simple use the main table: sip_capture_call without suffix to visualize the information.
I set: define('RTCP_TABLE_PARTITION', 0);
But It doesn't work.

**Comment by lmangani** [comment]
Hi @isaiasanchez I'm not sure why you would want to do such thing, there's a good reason rotation exists. Maybe you can explain your requirements or what you're trying to achieve by doing so, and we can suggest a better approach. Disabling rotation will slowly kill the performance of your system and the ability to return results over time.

**Comment by isaiasanchez** [comment]
I understand that, but I am using another way to rotate these tables using DB partitioning procedures. I am using postgresql and until now we use inheritance + triggers to deal with table rotation, and with the new coming version 10 I rather use postgres native partitioning, in that way the capture routine and homer web only deal with one single table.

**Comment by lmangani** [comment]
If that's the case, the spirit of the project would be to cooperate on new ideas and features by discussing them with the core developers to make the best out of opportunities to benefit everyone back, wouldn't it?

**Comment by isaiasanchez** [comment]
I totally agree, I was just asking if it was the possibility to disable it. I am very newbie in Homer stuff, I am mostly a DBA. But as a Workaround I forced my partition system to use same structure as Homer: sip_capture_call_yyyymmdd, so homer web checks directly the partition table for calls instead of master table, it works fine, 'cause master don't have any info.
I am going to submit a pull request with this idea to discuss it, also I am going to check if something similar can be done in MySQL to generate some SQL scripts for both RDBMS, and probably will be easier to maintain.

**Comment by isaiasanchez** [comment]
I am going to add my findings to this thread.

**Comment by adubovikov** [comment]
http://install.sipcapture.io/
