### ISSUE TITLE
Ipv6 calls are showing 0.0.0.0 ip when exported as pcap

### ISSUE THREAD

**Issue by acroitor** [sipcapture/homer-api#167]
Hi,

When displaying IPv6 calls in homer, the src and dest IPs are shown correctly in the GUI, but if you export the call as pcap, they are not saved correctly. If I open the pcap file with wireshark, it displays the ip as 0.0.0.0.
I have encountered this problem both in homer 3 and homer 5 versions. In homer 5, in Search.php, generateHomerTextPCAP(...) function handles the IPv4 case, but not the IPv6 one.

Thank you.

**Comment by acroitor** [comment]
Hello guys,

I have been trying to solve this issues, but I still have some problems signalled by wireshark.

Could you please take a look at the code here?  https://github.com/acroitor/homer-api/commit/2d151f609c04be861afff0d29d37534232e5a899 

Is it OK to open a pull request and continue the discussion there?

Thank you,
Andrei

**Comment by acroitor** [comment]
Hi,

I managed to successfully export a call that contained ipv6 IPs as pcap and open it with wireshark and it looks ok.

Thanks and regards,
Andrei

**Comment by lmangani** [comment]
@acroitor thanks for your PR, we'll review it asap! very much appreciated!

**Comment by lmangani** [comment]
Thanks again for your contribution, Andrei!

**Comment by adubovikov** [comment]
http://install.sipcapture.io/
