### ISSUE TITLE
click on Call-ID field does not display entire dialog if call started > 15 minutes before packet clicked

### ISSUE THREAD

**Issue by dancapper** [sipcapture/homer-api#171]
Search any long call
Click the "Call-ID" field for a late packet in the call
Expected behaviour: Entire dialog is shown for that call-id
Actual behaviour: Only part of the dialog is shown, starting about 15 minutes before that packet
Clicking an early packet in the call has the expected outcome

**Comment by adubovikov** [comment]
https://github.com/sipcapture/homer-ui/blob/0f0ccf0c45b290d4a2661bc54f34f22370c3ef5e/js/modules/pages/controllers/resultCtrl.js#L319

this is here. You can extend it.

**Comment by adubovikov** [comment]
Just changed it to be more flexible:
https://github.com/sipcapture/homer-ui/commit/858424f138a56f7d8c4a6f152c92e4a2acbef7e3
https://github.com/sipcapture/homer-ui/commit/68f239fcd3f702665d605f22d03a123783a08663

**Comment by adubovikov** [comment]
http://install.sipcapture.io/
