### ISSUE TITLE
Wrong MOS calculation

### ISSUE THREAD

**Issue by lishubing** [sipcapture/homer-api#172]
According to [ITU-G.107](https://www.itu.int/rec/T-REC-G.107-201506-I/en) Table 3, the unit of packet loss in MOS calculation is percentage, but in the function [calculateJitterMos](https://github.com/sipcapture/homer-api/blob/8b4cb91f76407428c7da37578c7ce9dbfa2f97af/api/RestApi/Report.php#L868), the count of packet loss is taken to calculate MOS, result goes all wrong due to the issue.

**Comment by adubovikov** [comment]
this fake mos, because according ITU you should have RTT  (round trip
time). In our case we use Jitter value. Feel free to correct it if you
think there is something wrong ;-)

**Comment by lishubing** [comment]
It's reasonable to estimate RTT with jitter value. 

The problem is homer use count of packet loss instead of percentage of packet loss in the calculation, in this way the loss of packet loss is exaggerated, finally the mos value become irregularly low. 

From the code we can tell the impact factor of packet loss is 2.5, which means packet loss of 40% should be regarded as unacceptable. But in this issue, after the conversation lost 40 packets, the mos value was considered to be unacceptable no matter how many packets had been transferred in total.

**Comment by lmangani** [comment]
Thanks for your comments @lishubing please feel free to submit a PR for discussion and testing

**Comment by mtryfoss** [comment]
This seems related to https://github.com/sipcapture/homer/issues/258

@lishubing , any thoughts regarding using packet loss delta instead of cumulative?

**Comment by adubovikov** [comment]
let us know if we can close the ticket. The PR has been merged.

**Comment by lishubing** [comment]
@mtryfoss In my own MOS calculation, the packet-loss factor is:

`  $data['report_blocks']['packets_lost'] / $data['sender_information']['packets'] * 100`

It seems reasonable for me, do you have any suggestion?

**Comment by adubovikov** [comment]
http://github.com/sipcapture/homer-app
