### ISSUE TITLE
incorrect content-length on json widget download (off by one)

### ISSUE THREAD

**Issue by davehorton** [sipcapture/homer-api#176]
I've got a strange problem on one of my systems.  When I download a large json widget file (specifically, `/api/v1/dashboard/store/_1428431423814`), there appears be to an extra carriage return/newline at the top of the http body, causing the `Content-Length: 342820` to be off by one, and the JSON parser in the browser to then throw an exception 'Unexpected end of input'

To show this, when I get a tcpdump from the server (/container, as I am running the homer-webapp image in k8s), the request and response looks like this:

```
GET /api/v1/dashboard/store/_1428431423814 HTTP/1.1
Host: homer.voxboneworkshop.com
Connection: keep-alive
X-Forwarded-For: 10.0.2.1
X-Forwarded-Proto: https
X-Forwarded-Host: homer.voxboneworkshop.com
X-Forwarded-Port: 8443
X-Real-IP: 10.0.2.1
Pragma: no-cache
Cache-Control: no-cache
Accept: application/json, text/plain, */*
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.140 Safari/537.36
Referer: https://homer.voxboneworkshop.com/
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9
Cookie: HOMERSESSID=kfmj7vlt7q9c2q9d163klp8to1

HTTP/1.0 200 OK
Date: Wed, 07 Feb 2018 16:32:44 GMT
Server: Apache/2.4.10 (Debian)
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
Pragma: no-cache
Content-Length: 342820
Connection: close
Content-Type: application/json; charset=utf-8

<== this is an extra CRLF
{
    "status": 200,
    "data": {
        "title": "Stats: VoIP Traffic",
  ...etc...
```
If I look at the content generated with that extra line feed, the length is indeed 342821, one byte more than is being reported.

However, I can not recreate this when running homer-complete on my local docker environment -- in that case the payload is generated *without* that extra line feed, and everything else exactly the same (and, of course, the content length is now accurate at 342820).

Also, on the system where this *does* happen, it only seems to happen on the larger/largest json payloads.  Other json downloads do occur *with* the extra CRLF but also *with* a properly-calculated Content-Length that takes this into account.  Here is an example of download that has the extra CRLF but in this case the Content-Length properly accounts for it and the browser parses it without error
```
GET /api/v1/dashboard/store HTTP/1.1
Host: homer.voxboneworkshop.com
Connection: keep-alive
X-Forwarded-For: 10.132.0.4
X-Forwarded-Proto: https
X-Forwarded-Host: homer.voxboneworkshop.com
X-Forwarded-Port: 8443
X-Real-IP: 10.132.0.4
Pragma: no-cache
Cache-Control: no-cache
Accept: application/json, text/plain, */*
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.140 Safari/537.36
Referer: https://homer.voxboneworkshop.com/
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9
Cookie: HOMERSESSID=kfmj7vlt7q9c2q9d163klp8to1

HTTP/1.0 200 OK
Date: Wed, 07 Feb 2018 16:32:44 GMT
Server: Apache/2.4.10 (Debian)
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
Pragma: no-cache
Content-Length: 1860
Connection: close
Content-Type: application/json; charset=utf-8


{
    "status": 200,
    "data": [
        {
            "name": "SIP Search",
            "href": "search",
            "class": "fa fa-search",
            "id": "_1426001444630"
        },
        {
            "name": "Alarms",
            "href": "alarms",
            "class": "fa fa-warning",
            "id": "_1431721484444"
        },
        {
            "name": "Panels",
            "href": "#",
            "class": "fa fa-dashboard",
            "rowclass": "fa fa-angle-left pull-right",
            "subItems": [
                {
                    "boardid": "_1427728371642",
                    "name": "Home",
                    "class": "fa fa-angle-double-right"
                },
                {
                    "boardid": "_1452069187383",
                    "name": "Geo Chart",
                    "class": "fa fa-angle-double-right"
                },
                {
                    "boardid": "_1411848944046",
                    "name": "Stats: IP Network",
                    "class": "fa fa-angle-double-right"
                },
                {
                    "boardid": "_1450278390101",
                    "name": "Get Started",
                    "class": "fa fa-angle-double-right"
                },
                {
                    "boardid": "_1428431423814",
                    "name": "Stats: VoIP Traffic",
                    "class": "fa fa-angle-double-right"
                },
                {
                    "boardid": "_1428431423814.save",
                    "name": null,
                    "class": "fa fa-angle-double-right"
                },
                {
                    "boardid": "_1430318378410",
                    "name": "System Admin",
                    "class": "fa fa-angle-double-right"
                }
            ]
        }
    ]
}
```
The one difference on this system that is having the problems is that I copied these .json widget files in there (`/var/www/html/store/dashboard`) from a homer-ui checkout because I wanted to reset the gui back to the original default state.  The files look fine, however, have no extra line feeds and parse fine themselves as json.  Also, the extra CRLF seems to be occurring after the php code has wrapped this json content into a bigger response object (i.e., as the `data` property) so I can't see how that might have caused it.

Any thoughts on how to troubleshoot this?

**Comment by davehorton** [comment]
This happens not only on file downloads, but also GET requests to `api/v1/search/data` -- again, only if the amount of data is large enough.  If I filter only one or a few records, they display but if I bring back 1000 then the content length is off and I get a JSON parse error as a result

**Comment by davehorton** [comment]
I'm noticing that the latest checked-in homer-api has this:
```
    public function setContentLength($pMessage)
    {
	//Fix for MAC Safary and Chrome + 2 for response
        if (php_sapi_name() !== 'cli' )
            header('Content-Length: '.strlen($pMessage)+2);
    }
```
while my running container has this:
```
    public function setContentLength($pMessage)
    {
        if (php_sapi_name() !== 'cli' )
            header('Content-Length: '.strlen($pMessage));
    }
```
This looks like it could be the cause, I will investigate updating my image

**Comment by davehorton** [comment]
ok so it looks like it was fixed in this commit:
https://github.com/sipcapture/homer-api/commit/ec17e43fe060b456958bfccbaa1b6e3e5aaf3529
but the homer-complete image does not include it:
https://github.com/sipcapture/homer-docker/blob/master/webapp/Dockerfile#L20

I can deploy that fix and build my own image, but wondering if there is plans to release a new homer-complete image at some point with this fix?  

If my diagnosis is faulty please let me know

**Comment by lmangani** [comment]
Thanks for the update @davehorton - I guess all we need is retrigger the Docker builders. I'm trying so now, will confirm once ready to retest, please standby

**Comment by adubovikov** [comment]
http://install.sipcapture.io/
