### ISSUE TITLE
Large INVITEs > 1500 bytes not being saved

### ISSUE THREAD

**Issue by davehorton** [sipcapture/homer-api#177]
I am running some siprec traffic where the large multipart payloads can easily cause the size of INVITEs to exceed 1500, which is the size of the `msg` column in several tables.  The impact is that these calls  do not appear in the tables (well, the 100 Trying etc does but not the initial INVITE).  I actually tried modifying the column size in mysql to 4096 but still am not seeing these messages.  Any idea of a workaround that would let me store and retrieve these larger INVITE messages?

**Comment by lmangani** [comment]
Hi Dave,
Check this out: https://github.com/sipcapture/homer-api/blob/master/scripts/mysql/rotation.ini#L78

Let me know if this sorts it.

**Comment by hamid-elaosta** [comment]
This doesn't appear to be useful for the Docker based versions. Even mounting this file externally as a volume, and increasing the SIP capture value, the DB is still created with the column too short for some of us with large INVITE packets. It would be useful to have this configurable for the Docker builds, or made larger by default to accommodate larger INVITEs.

**Comment by lmangani** [comment]
Hi @hamid-elaosta I updated the default for new builds - alternatively, you can mount your own rotation.ini with any preference you wish and/or build a custom rotation container with any settings of your likes. New versions of the stack shall no longer have this problem as the partitions are created by the capture-server itself.

**Comment by hamid-elaosta** [comment]
@lmangani Thanks. I've been building with rotation.ini mounted in but it doesn't affect DB creation, I've also tried mounting the `schema_data.sql` with modified values in the `docker-opensips` build I'm using but I presume it's run from another copy other than that in `/home-api/sql/mysql/data_schema.sql`? That copy has my changes but the opensips database is still created with the 1500 length.

**Comment by lmangani** [comment]
Partitions are created days in advance and existing one won't be modified by executions (unless you drop them ahead of running the rotation script) so keep this in mind as you test a solution.

**Comment by hamid-elaosta** [comment]
@lmangani Indeed. I am a clean db every startup, for some reason volume mounting the `rotation.ini` didn't affect table creation. Perhaps volumes are mounted after the tables are created?
I pulled your latest change from the homer-api repo and pre-building it with the correct value works fine now, thanks :+1: 

EDIT: At ~2700 character INVITEs I'm dangerously close to your 3000 limit already :sob:

**Comment by rs03** [comment]
Even I am facing same issue.Can somebody please help me here? I have modified sip_capture_call = 3000 in MSG_TABLE_SIZE(vim /usr/src/homer-api/scripts/mysql/rotation.ini) , I can see modified msg field size in sipcapturecall table but still not getting entire INVITE data

**Comment by adubovikov** [comment]
You should also activate the de-fragmentation/reassmbling for UDP/TCP
packets in your socket_pcap.xml file

**Comment by rs03** [comment]
Hi

Thanks for reply...yes i have set reasm to true and if I do so ..I don't
see fragmented packets in database/homer

**Comment by adubovikov** [comment]
check with wireshark and HEP dissector if you have received the full packet

**Comment by rs03** [comment]
checked with HEP dissector I am not getting entire SDP at homer server . 
![image](https://user-images.githubusercontent.com/37635175/48333406-47850300-e67d-11e8-939c-60744070db0c.png)

But I have made all the changes in socket_pcap.xml

**Comment by adubovikov** [comment]
http://install.sipcapture.io/
