### ISSUE TITLE
homer_mysql_rotate fails. 

### ISSUE THREAD

**Issue by JonConnor** [sipcapture/homer-api#178]
-sh-4.2$ sudo homer_mysql_rotate
DBI connect('homer_data:localhost:3306','homer_user',...) failed: Access denied for user 'homer_user'@'localhost' (using password: YES) at /usr/bin/homer_mysql_rotate.pl line 348.
Can't call method "do" on an undefined value at /usr/bin/homer_mysql_rotate.pl line 407.

After a new install of Homer 5, the scripts were not found in /usr/bin.  I manually copied the scripts and ini file to this directory, but is not running properly.

**Comment by lmangani** [comment]
Hi @JonConnor the scripts are usually located in /opt and depend on each other, with database credentials being provided by the `rotation.ini` parameters

**Comment by JonConnor** [comment]
awesome thanks.  updated rotation.ini fixed it
