### ISSUE TITLE
NO msg field when retrieved call details using GET/POST  http://localhost/api/v1/search/data

### ISSUE THREAD

**Issue by rs03** [sipcapture/homer-api#180]
I am getting msg field in sip_capture_calls_xxx table under homer_data database but when I retrieve call using GET method  , I don't see msg field at all.

Table schema :+1: 
| id  | date                | micro_ts         | method  | reply_reason | ruri                                       | ruri_user | ruri_domain                      | from_user  | from_domain                     | from_tag      | to_user | to_domain                        | to_tag | pid_user | contact_user | auth_user | callid                               | callid_aleg | via_1                                                                         | via_1_branch                                   | cseq              | diversion | reason | content_type | auth | user_agent                       | source_ip   | source_port | destination_ip | destination_port | contact_ip | contact_port | originator_ip | originator_port | expires | correlation_id                       | custom_field1 | custom_field2 | custom_field3 | proto | family | rtp_stat | type | node       | **msg** 

How Can I retrieve msg data using rest APIs? 

I have tried to POST above REST API, this time I get msg field but it contains nothing . I cross checked it in databases , it has data in msg field but not getting while retrieving using rest APIs

**Comment by adubovikov** [comment]
http://install.sipcapture.io/
