### ISSUE TITLE
Back-End homer-api for Java ?

### ISSUE THREAD

**Issue by livem** [sipcapture/homer-api#186]
Back-End homer-api now is a php server, 

is there a Java Back-End server ?

**Comment by adubovikov** [comment]
the homer-api project is for Homer 5 and it's obsolete. Please take a look
at Homer 7. The api server is base on nodejs

Wbr,
Alexandr

**Comment by livem** [comment]
Thanks. Where can I find Homer 7 ? Official website ?


On 11/16/2018 18:04，Alexandr Dubovikov<notifications@github.com> wrote：
the homer-api project is for Homer 5 and it's obsolete. Please take a look
to Homer 7. The api server is base on nodejs

Wbr,
Alexandr

**Comment by adubovikov** [comment]
http://github.com/sipcapture/homer-app
