### ISSUE TITLE
unable to send json using statstrmr to homer api

### ISSUE THREAD

**Issue by jackbreurkes** [sipcapture/homer-api#188]
when trying to send data using statstrmr to the homer api at http://localhost:8888/api/v1/stats/push, I get a 400 error RouteNotFoundException "'There is no route for \'stats/push'."
I get the same error when sending a POST request to the api. I have followed along with the [CustomStats example](https://github.com/sipcapture/homer/wiki/Example:-CustomStats) on the Homer wiki and everything seems to work apart from this.

**Comment by adubovikov** [comment]
http://github.com/sipcapture/homer-app
