### ISSUE TITLE
Seems Hardcoded Value in Search.php

### ISSUE THREAD

**Issue by lexxua** [sipcapture/homer-api#19]
Hello seems like SQL-script ignores 'DB_CONFIGURATION' from config :

$query .= " LEFT JOIN homer_configuration.alias as hcs ON t.source_ip=hcs.ip AND t.source_port=hcs.port LEFT JOIN homer_configuration.alias as hcd ON t.destination_ip=hcd.ip AND t.destination_port=hcd.port";

Thanks

**Comment by adubovikov** [comment]
fixed. Thanks for the report.

https://github.com/sipcapture/homer-api/commit/0b3cb6b73f3583da427f25b4835426a097e189f0

**Comment by lexxua** [comment]
Oh, thank you!
Just tested on my server, all works as expected.

**Comment by adubovikov** [comment]
you are welcome. Thanks for reporting...
