### ISSUE TITLE
does possible homer authenticat via microsoft active directory?

### ISSUE THREAD

**Issue by salehhoushangi** [sipcapture/homer-api#190]

**Comment by lmangani** [comment]
LOCAL and LDAP authentication are supported. You are although posting on an old project, please switch to H7 (homer-app)

**Comment by salehhoushangi** [comment]
yes but actually now i switched to H7 but unfortunately  after configured /opt/homer-app/server/config.js  like below :
const ldapauth = {
   url: 'ldap://10.0.xxx:389',
   strictDN: true,
   dn: 'dc=xx,dc=net',
   userdn: 'uid=%USERNAME%',
   filter: '(uid=%USERNAME%)',
   scope: 'sub',
   uidNumber: 'uidNumber'

and 
auth: {
    ldap: true,
i cant success to authenticate via AD. and giving error "Error: Something went wrong, no JWT token received, probably wrong credentials used to login"
any more change must be need  to do ?
i dont know where we should define user that can authenticate  homer7 with and how to define user as admin to authenticate in homer 7 via AD
