### ISSUE TITLE
MySQL 8: function PASSWORD() removed.

### ISSUE THREAD

**Issue by hb9eue** [sipcapture/homer-api#193]
Dear Team

Following https://nickvsnetworking.com/setup-homer-ui-on-ubuntu-18-04/ for a manual install from github, as Debian 9 ist EOL and CentOS is a NoGo.

Stumbled over this Database insert from: homer-api/sql/mysql/schema_configuration.sql

INSERT INTO `user` (`uid`, `gid`, `grp`, `username`, `password`, `firstname`, `lastname`, `email`, `department`, `regdate`, `lastvisit`, `active`) VALUES
(1, 10, 'users,admins', 'admin', PASSWORD('test123'), 'Admin', 'Admin', 'admin@test.com', 'Voice Enginering', '2012-01-19 00:00:00', '2015-05-29 07:17:35', 1),
(2, 10, 'users', 'noc', PASSWORD('123test'), 'NOC', 'NOC', 'noc@test.com', 'Voice NOC', '2012-01-19 00:00:00', '2015-05-29 07:17:35', 1);

PASSWORD() was deemed insecure by MySQL and thus removed in the Version 8

**Comment by hb9eue** [comment]
Close, only now realized, this install obsolete version 5.

**Comment by lmangani** [comment]
This is the current one: https://github.com/sipcapture/homer-app
