### ISSUE TITLE
schema_capture.sql fails

### ISSUE THREAD

**Issue by nshopik** [sipcapture/homer-api#2]
When I try to execute `schema_capture.sql` it fails with error
`ERROR 1064 (42000) at line 9: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'AUTO_INCREMENT=1' at line 24`

If I remove /*! MySQL-specific code */ it appears to be working at least for first table creation.

**Comment by adubovikov** [comment]
fixed. check the last git.

**Comment by nshopik** [comment]
looks good now
