### ISSUE TITLE
Udef Variable Result

### ISSUE THREAD

**Issue by lexxua** [sipcapture/homer-api#21]
Hello, every time search executed php throws string to error log:
Notice: Undefined variable: result in /srv/www/api/Database/PDOConnector.php on line 151
Maybe SQL query: [SET time_zone = "+00:00";] causes this.
Is it bug or not ?
Thank you.

**Comment by adubovikov** [comment]
https://github.com/sipcapture/homer-api/commit/c82af54459f864ba65dfe65852ffccb44532cce1
