### ISSUE TITLE
How to get PDD (post deal delay) in Homer

### ISSUE THREAD

**Issue by vasyl-shumskyi** [sipcapture/homer-api#26]
Hi guys,

How do I get post deal delay (PDD) info in Homer? I went trough database schema but didn't find such table field.. Looks like there is no much information across Internet on this as well.. The one found is Alexandr Homer-Shooting presentation, where PDD is getting with sipgrep  http://www.kamailio.org/events/2014-KamailioWorld/day2/21-Alexandr.Dubovikov-Homer-Shooting.pdf 

<img width="960" alt="screen shot 2015-07-14 at 16 35 49" src="https://cloud.githubusercontent.com/assets/2331802/8674470/cab09d44-2a46-11e5-9617-ba28136ef903.png">

Thanks!

**Comment by adubovikov** [comment]
Vasyl,

please don't open issue if you have just question, For such things we have mail-list.
