### ISSUE TITLE
kamailio mysql errors on insertion

### ISSUE THREAD

**Issue by nshopik** [sipcapture/homer-api#3]
After copy example kamailio config make local changes and starting kamailio I'm getting these errors:

```
db_mysql [km_dbase.c:121]: db_mysql_submit_query(): driver error on query: Table 'homer_data.sip_capture_call_20150619' doesn't exist
<core> [db_query.c:235]: db_do_insert_cmd(): error while submitting query
```

From kamailio config I don't see where it suppose to create such tables, only tries to insert data

**Comment by lmangani** [comment]
Nikolay,

Did you install the scrpts povided and schedule the daily creation/rotation in cron?

**Comment by adubovikov** [comment]
did u run rotate.sh before ?

**Comment by nshopik** [comment]
Nope, I was assume they only need after day passed (installation doc doesn't mention run it before).

There also some naming conflict database names some scripts are saying database should be named homer_statistic and sql files says homer_statistics

**Comment by adubovikov** [comment]
it was mistyping in the doc. The db name should be not in plural.

thank you!

**Comment by nshopik** [comment]
Sure, also rotate.sh have dos ending, which prevent it working on unix unless converted

And after I've run rotate.sh now I'm seeing these errors, is this normal?

```
ERROR: htable [ht_api.c:1444]: ht_iterator_start(): cannot get hash table [c]
ERROR: htable [ht_api.c:1477]: ht_iterator_next(): iterator not initialized [i1]
```

**Comment by adubovikov** [comment]
please make a pull request to fix rotate.sh.

about htable error:

this happens if htable was not initialized and you try to get value from there. Normally you can ignore, but later we should check it more deep.
