### ISSUE TITLE
Api issue with multinodes

### ISSUE THREAD

**Issue by Mickaelh51** [sipcapture/homer-api#30]
Hi,
there is an issue when I want show SIP stream when I click on call-id.

Apache errors:

[Wed Jul 29 10:46:14.857728 2015] [:error] [pid 27646] [client XXXXX041] PHP Notice:  Undefined variable: lnodes in /var/www/homer-ui/api/RestApi/Search.php on line 536, XXXX
[Wed Jul 29 10:46:14.857760 2015] [:error] [pid 27646] [client XXXX51041] PHP Warning:  Invalid argument supplied for foreach() in /var/www/homer-ui/api/RestApi/Search.php on line 536, XXXX

endeed, in Json POST there is no node
{"timestamp":{"from":1438153042857,"to":1438157113028},"param":{"search":{"id":5362,"callid":["3200762-3647140992-581717@XXXXXX"]},"location":{"node":[]},"transaction":{"call":true,"registration":false,"rest":false}}}

thanks

**Comment by adubovikov** [comment]
Can u please provide also json of transaction search ?

**Comment by Mickaelh51** [comment]
Json POST from search

{"param":{"transaction":{"call":true,"registration":true,"rest":true},"limit":200,"search":{"from_user":"","to_user":"","ruri_user":"","limit":""},"node":[{"id":"22","name":"capturenode1"},{"id":"23","name":"capturenode2"}]},"timestamp":{"from":1438146313028,"to":1438157113028}}

**Comment by adubovikov** [comment]
please check it
https://github.com/sipcapture/homer-ui/commit/b4241204e172bf33ed2bf4beafcda02548f64a71

**Comment by adubovikov** [comment]
any progress ?

**Comment by kemathy** [comment]
Hi Alexandr, 

Mickael will not be available for two weeks, so I'll take care of our Homer5 tests meanwhile :-)
I've tried using the latest git, and the result is all the same... 
Hope you'll be able to help us !

Thanks, 
Kevin

**Comment by adubovikov** [comment]
Hi Kevin,

can you please provide both JSON requests ? (search and transaction view)

thank you.

Wbr,
Alexandr

**Comment by adubovikov** [comment]
and please also provide php error log

**Comment by kemathy** [comment]
Hi Alexandr, 

I don't know if I'm right, but here is the JSON requests you asked for : 

{"param":{"transaction":{"call":true},"limit":200,"search":{"from_user":"","to_user":"","ruri_user":"","limit":""},"node":[{"id":"22","name":"capturenode1"},{"id":"23","name":"capturenode2"}]},"timestamp":{"from":1437282313028,"to":1438761913028}}

Also, here are the PHP error logs : 
[Wed Aug 05 15:27:11.473423 2015] [:error] [pid 16827] [client XX.XX.XX.XX:49661] Array\n(\n    [0] => 42S02\n    [1] => 1146\n    [2] => Table 'homer_data.sip_capture_call_20150805' doesn't exist\n)\n, referer: http://xxxxxx.xxxxxxx.xxxxxxxx/
[Wed Aug 05 15:27:16.111504 2015] [:error] [pid 16761] [client XX.XX.XX.XX:49666] PHP Notice:  Undefined variable: lnodes in /var/www/homer-ui/api/RestApi/Search.php on line 536, referer: http://xxxxxx.xxxxxxx.xxxxxxxx/
[Wed Aug 05 15:27:16.111540 2015] [:error] [pid 16761] [client XX.XX.XX.XX:49666] PHP Warning:  Invalid argument supplied for foreach() in /var/www/homer-ui/api/RestApi/Search.php on line 536, referer: http://xxxxxx.xxxxxxx.xxxxxxxx/

Thanks for your help, 

Kevin

**Comment by adubovikov** [comment]
i think your new_table script doesn't work (sip_capture_call_20150805' doesn't exist). Please provide also search json.

**Comment by kemathy** [comment]
You're right, it's possible that cron isn't configured, so new tables aren't created... I'll try execute it, if you think it can solve our problem.

Also, here is JSON :
{"id":"search","param":{"from_user":"","to_user":"","ruri_user":"","limit":""}}

It's a bit small, so I don't know if it's the right one; tell me if you need something else !

Thanks, 
Kevin

**Comment by adubovikov** [comment]
no, this is wrong one. Did you select all dbnodes for search ?

**Comment by kemathy** [comment]
Hi Alexandr, 

I'm sorry for the latency between your answer and mine... I've selected all dbnodes for search, and re-done it this morning; here are the result : 

When I click on search, if I select both capture nodes, and set no other parameter (no RURI, or anything else), I can see following POST requests :
- Search
  URL : https://xxxxxxxxxxxxxxxxx/api/profile/store/search
  Parameters : {"id":"search","param":{"from_user":"","to_user":"","ruri_user":"","limit":""}}
- Transaction 
  URL : https://xxxxxxxxxxxxxxx/api/profile/store/transaction
  Parameters : {"id":"transaction","param":{"transaction":[{"name":"call","value":"CALLS"}]}}
- Result 
  URL : https://xxxxxxxxxxxxxx/api/profile/store/result
  Parameters : {"id":"result","param":{"restype":{"name":"table","value":"TABLE"}}}
- Node 
  URL : https://xxxxxxxxxx/api/profile/store/node
  Parameters : {"id":"node","param":{"node":{"name":"localhost","id":"localhost"},"dbnode":[{"id":"22","name":"capturenode1"},{"id":"23","name":"capturenode2"}]}}
- Data 
  URL : https://xxxxxxxxxxxxxxxx/api/search/data
  Parameters : {"param":{"transaction":{"call":true},"limit":200,"search":{"from_user":"","to_user":"","ruri_user":"","limit":""},"node":[{"id":"22","name":"capturenode1"},{"id":"23","name":"capturenode2"}]},"timestamp":{"from":1437282313028,"to":1438761913028}}

I hope the right one is here :-) !

Feel free to tell me if you need further informations.

Kevin

**Comment by kemathy** [comment]
Hi Alexandr, 

Were there all the informations you needed, in my previous message ? 

Don't hesitate to tell if there's something else you need ;-)

Thanks, 
Kevin

**Comment by adubovikov** [comment]
Hi Kevin,

i am working on this issue, please provide your preferences.php as well.

thank you

Wbr,
Alexandr

**Comment by kemathy** [comment]
Hi Alexandr, 

OK, no problem !

Here is our preferences.php file : http://pastebin.com/LKW9EL6d

Thanks,
Kevin

**Comment by adubovikov** [comment]
thank you, can you please also paste configuration.php without passwords/credentials ?

**Comment by kemathy** [comment]
Here it is : http://pastebin.com/6GnrSx4E

Thanks, 
Kevin

**Comment by adubovikov** [comment]
Kevin,

please update api and ui  and check again.

thank you!

Wbr,
Alexandr

**Comment by kemathy** [comment]
Hi Alexandr, 

It seems to be OK now, I can see the call-flow !
The only thing is that it doesn't seem possible to scroll along the call-flow, to see it entirely, but it's an UI issue, so, I'll open a case in the right github repo ;-)

Kevin

**Comment by adubovikov** [comment]
ok, closed!
