### ISSUE TITLE
Call-flow graph create additional node 

### ISSUE THREAD

**Issue by nshopik** [sipcapture/homer-api#37]
Call-flow mode assume that endpoint is strict IP:PORT. This create additional node in call-flow graphs, if my node send request from one port and expect answer on different port (contact header). 

Here example how it looks like, where 10.10.10.10 is same node in term of callflow.

10.10.10.10:65000->172.16.1.1:5060->10.10.10.10:5600

Personally I like how wireshark make callflow graph (where port number shows at end of arrow)

**Comment by adubovikov** [comment]
please read preferences_example.php, there are all parameters
https://github.com/sipcapture/homer-api/blob/master/api/preferences_example.php#L8
