### ISSUE TITLE
problem with deleting old tables

### ISSUE THREAD

**Issue by qnox81** [sipcapture/homer-api#38]
Hi!

SQL for deleting old table in homer_mysql_new_table.pl in line 111 is broken, bellow patch should fix it:

root@homer:/opt/scripts# diff -urN homer_mysql_new_table.pl.new homer_mysql_new_table.pl.org
--- homer_mysql_new_table.pl.new        2015-08-12 16:19:12.023200107 +0200
+++ homer_mysql_new_table.pl.org        2015-08-12 16:17:28.939024179 +0200
@@ -108,7 +108,7 @@
 PARTITION pmax VALUES LESS THAN MAXVALUE ENGINE = InnoDB) */ ;
 END

-$DROP="DROP TABLE IF EXISTS `sip_capture_[TRANSACTION]_[TIMESTAMP]`;";
+$DROP="DROP TABLE IF EXISTS `sip_capture_[TRANSACTION]_[TIMESTAMP];`";

 $db = DBI->connect("DBI:mysql:$mysql_dbname:$mysql_host:3306", $mysql_user, $mysql_password);
 #$db->{PrintError} = 0;

**Comment by adubovikov** [comment]
Hi, sorry, but i don't really see that is broken, Can you please make merge request ?

**Comment by adubovikov** [comment]
ah, i see, ";" is in the table name...

thanks for report!
