### ISSUE TITLE
Make variable at top kamailio.cfg for interval time

### ISSUE THREAD

**Issue by nshopik** [sipcapture/homer-api#4]
Currently default is 5min but some people prefer better granulation, but you have to dig into cfg file to find what need to change. So It be nice to have variable at top of config for easier management.

https://github.com/sipcapture/homer-api/blob/master/examples/sipcapture/kamailio.cfg#L459
https://github.com/sipcapture/homer-api/blob/master/examples/sipcapture/kamailio.cfg#L462

**Comment by adubovikov** [comment]
https://github.com/sipcapture/homer-api/commit/aa097505ef6aef878f97043735c64e1b5ff65c41

**Comment by nshopik** [comment]
Awesome, Thanks!
