### ISSUE TITLE
Strange search behaviour

### ISSUE THREAD

**Issue by lexxua** [sipcapture/homer-api#43]
Greetings, after reinstall homer-api from scratch I get following stuff during search request:

{
    "status": 500,
    "error": "PDOException",
    "message": "SQLSTATE[42000] [1064] You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '-ui.alias as hcs ON t.source_ip=hcs.ip AND t.source_port=hcs.port LEFT JOIN home' at line 3"
}
Maybe I misconfigured something ?
Thanks.

**Comment by adubovikov** [comment]
show your configuration.php

**Comment by lexxua** [comment]
And here we go. Previously I had UI and Data in same Db.

<?php

if(!defined('HOMER_CONFIGURATION')):
define('HOMER_CONFIGURATION', 1);

/********************************************************************************_/
/_ AUTH DB homer. User and Configuration */

define('DB_HOSTNAME', "10.10.16.40");
define('DB_PORT', 3306);
define('DB_USERNAME', "homer");
define('DB_PASSWORD', "l.FavbI873");
define('DB_CONFIGURATION', "homerv5-ui");
define('DB_STATISTIC', "homerv5");
define('DB_HOMER', "homerv5");
define('SINGLE_NODE', 1);

/*********************************************************************************/

/\* webHomer Settings
-  Adjust to reflect your system preferences
  */

define('PCAPDIR', ROOT."/tmp/");
define('WEBPCAPLOC',"/tmp/");

/\* INCLUDE preferences */

include_once("preferences.php");

endif;

?>

**Comment by adubovikov** [comment]
try to rename db to "homerv5_ui", don't use "-" for tables and dbs

**Comment by lexxua** [comment]
I changed db name and all works as expected. 
Thank you!
