### ISSUE TITLE
Aliasses are not applied on remote nodes

### ISSUE THREAD

**Issue by michaelarnauts** [sipcapture/homer-api#48]
I have a multi-node setup where on the 2nd node only has a MySQL and Kamailio running.

Aliasses defined in the UI are only saved locally, so calls returned from the 2nd node don't have the configured aliasses applied.

It seems that the aliasses are applied by using a LEFT JOIN in MySQL itself, but this ofcourse doesn't work on the 2nd node that doesn't have the aliasses.

I guess a proper solution would be to apply the aliasses in code before returning the results to homer-ui.

**Comment by adubovikov** [comment]
agree. This was in first release, need to reverese the code. We will do it ASAP.
