### ISSUE TITLE
Permissions: Users in the "user" group can modify all dashboards.

### ISSUE THREAD

**Issue by michaelarnauts** [sipcapture/homer-api#49]
Users in the "user" group can modify all dashboards. There doesn't seem to be a configuration option for this.

**Comment by adubovikov** [comment]
we will implement this feature in the next release

**Comment by adubovikov** [comment]
implemented.

https://github.com/sipcapture/homer-ui/commit/d63e186a9e4a01fc04843072f276f3cc1d358a6d
https://github.com/sipcapture/homer-api/commit/083e217a576cb743cc1bcd374b775c544806a23c
