### ISSUE TITLE
db_mysql_submit_query(): driver error on query: Table 'homer_data.sip_capture_call_20151203' doesn't exist

### ISSUE THREAD

**Issue by yuvalcnaan** [sipcapture/homer-api#61]
After few days kamailio can't write to mysql....why ? who is creating new table every day?

mysql> show tables;
+-----------------------------------+
| Tables_in_homer_data              |
+-----------------------------------+
| logs_capture                      |
| report_capture                    |
| rtcp_capture                      |
| sip_capture_call_20151129         |
| sip_capture_call_20151130         |
| sip_capture_call_20151201         |
| sip_capture_registration_20151129 |
| sip_capture_registration_20151130 |
| sip_capture_registration_20151201 |
| sip_capture_rest_20151129         |
| sip_capture_rest_20151130         |
| sip_capture_rest_20151201         |
+-----------------------------------+

Thanks!

Yuval Cnaan

**Comment by adubovikov** [comment]
rotation script.

https://github.com/sipcapture/homer/wiki/Quick-Install#mysql

Wbr,
Alexandr

**Comment by yuvalcnaan** [comment]
homer 5 as well ?

**Comment by adubovikov** [comment]
yes, the scripts should be installed in both versions.

Wbr,
Alexandr

**Comment by yuvalcnaan** [comment]
Thanks! i run it manually  
/usr/bin/homer_rotate .....
in
/etc/cron.d/sipcapture

Centos 7

Thanks!

**Comment by adubovikov** [comment]
you are welcome
