### ISSUE TITLE
Search problem with non-standard DB port

### ISSUE THREAD

**Issue by apogrebennyk** [sipcapture/homer-api#65]
I was getting the following error in Firebug during search request:
{
    "status": 500,
    "error": "PDOException",
    "message": "SQLSTATE[HY000] [2003] Can't connect to MySQL server on '127.0.0.1' (111)"
}
At the same time the statistics are showing well. The DB is reachable on localhost port 3213 (it's haproxy listener). 

The data in node table seems correct:
mysql> select \* from node;
+----+-----------+------------+--------+------------+------------------+-------------+------+--------+
| id | host      | dbname     | dbport | dbusername | dbpassword
| dbtables    | name | status |
+----+-----------+------------+--------+------------+------------------+-------------+------+--------+
| 22 | 127.0.0.1 | homer_data | 3213   | sipcapture | xxxx
| sip_capture | RDS  |      1 |
+----+-----------+------------+--------+------------+------------------+-------------+------+--------+
1 row in set (0.01 sec)

I can login with this host, port and password:

root@1378bdbb84dd:/var/tmp# mysql -u sipcapture -h127.0.0.1 -P 3213
homer_data -p
Enter password:
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A 
...

I've added another haproxy listener on localhost port 3306 and search works well now.
To me it looks like some of the PHP classes are connecting to default port 3306 instead of the port defined in node table.
Could you please follow up? Thanks.

**Comment by giavac** [comment]
I can instruct searches to use non-standard ports. Out of curiosity, what's the DB_PORT value in your api/configuration.php?

**Comment by apogrebennyk** [comment]
Giacomo, DB_PORT is 3213:
define('DB_PORT', 3213);
Thanks.

**Comment by lmangani** [comment]
Closing - Please feel free to re-open if useful
