### ISSUE TITLE
Provide a way to store mysql_user and mysql_password in one place

### ISSUE THREAD

**Issue by michaelarnauts** [sipcapture/homer-api#66]
It would be easier if the `homer_mysql_new_table.pl`, `homer_mysql_partrotate_unixtimestamp.pl` and `homer_rotate` files could fetch the mysql user and password information from one place. That way, the files are unmodified in the local git. 

I also have to change `sipcapture.kamailio`, but I don't think there is a way around that, unless maybe some build script is added to generate those files based on the files in the repository?

Ideally, a git status should give no changes (since configuration files should be in `.gitignore`) on a fully configured system.

**Comment by adubovikov** [comment]
please make modification and a merge request. We will accept it ASAP.
the ideally will be create a config file i.e. /etc/homer/rotate.conf and read this information from there.

**Comment by michaelarnauts** [comment]
Okay, but in the past, the configuration files were like `preferences_example.php`, and now they are moved to `preferences.php`. This makes it impossible for those files to be excluded in a `.gitignore`.
According to the commit message, this was done for some packaging changes.

**Comment by lmangani** [comment]
@michaelarnauts just thinking out loud here, if the only changes are configuration files wouldn't simply stashing and restoring after a pull should do the trick? `git stash && git pull && git stash pop`

This being said a .gitignore config file as Alexandr suggest could do the trick and provide details for all scripts/files requiring them with some work or via an update script.

**Comment by michaelarnauts** [comment]
@lmangani true, but that tend to give conflicts when changes in those files are also made.

The cleanest way is to have a configuration.php.example file, and upon installation, copy that to a configuration.php file, what is ignored trough a .gitignore. At least, that's how most projects do it. I just don't know how that relates to the packaging changes that are being made the in the last weeks/months.

**Comment by lmangani** [comment]
We will quickly discuss the package implications and how to implement this best

**Comment by lmangani** [comment]
@michaelarnauts implemented, the filenames are restored to their _correct_ names now as they were - thanks for raising this and please confirm back to close the issue

**Comment by michaelarnauts** [comment]
@lmangani you need to remove the configuration.php and preferences.php, and add those to .gitignore. Otherwise, they are still marked as changed on a git pull.

This also doesn't resolve this issue, since all scripts still need to be changed. This issue is to have one place where the configuration is stored.

**Comment by adubovikov** [comment]
sorry, but we did it. Please check homer-api git

**Comment by michaelarnauts** [comment]
@adubovikov sorry, I only checked the latest commit :)

I think we still need a way to have one configuration file that is easy parsable with PHP and Perl.

**Comment by adubovikov** [comment]
the configurations for php and for rotation scripts should be separated,
because you can have multiple DBs, but only one web UI.

so, the idea to create one config for rotation scripts is not bad, but only
for rotations scritps.

**Comment by adubovikov** [comment]
testers are welcome

https://github.com/sipcapture/homer-api/tree/master/scripts/new
