### ISSUE TITLE
Only one column can have a DEFAULT CURRENT_TIMESTAMP.

### ISSUE THREAD

**Issue by michaelarnauts** [sipcapture/homer-api#67]
Apparantly, only one column can have a DEFAULT CURRENT_TIMESTAMP.

da8b25b7715c3f92c20de2807c3eefcb42f0a7fc broke this in the schema_statistics.sql

```
ERROR 1293 (HY000) at line 76: Incorrect table definition; there can be only one TIMESTAMP column with CURRENT_TIMESTAMP in DEFAULT or ON UPDATE clause
```

**Comment by adubovikov** [comment]
mysql version ?

**Comment by adubovikov** [comment]
anyway, 5.6.5 allows it, but we can make compatibility to < 5.6 and close the issue.

**Comment by adubovikov** [comment]
https://github.com/sipcapture/homer-api/commit/764f0c2f464d2cb3e029d7e9d15a1691b07bbd06
