### ISSUE TITLE
Working examples for Custom Stats

### ISSUE THREAD

**Issue by ishmaelen** [sipcapture/homer-api#74]
Hello,

The "HOMER_CUSTOM_STATS" in current Kamailio config example [found here](https://github.com/sipcapture/homer-api/blob/master/examples/sipcapture/sipcapture.kamailio) is not in accordance with the current example for CustomStats found [here](https://github.com/sipcapture/homer/wiki/Example%3A-CustomStats).

I tried using the plain default examples but the error below appeared in Kamailio log as shown below when receiving data from statsmrtr.

Also please include RTCP stats in the same configuration examples; something like

`if($var(n) == "rtp_stat") {`
`.....`
`else if($var(n) == "rtcp_stat") {`

etc.
### Kamailio log

`WARNING: HTTP request received on 8080, /api/v1/stats/push`
`WARNING: Type is rtp_stat`
`ERROR: <core> [lvalue.c:345]: lval_pvar_assign(): non existing right pvar`
`ERROR: <core> [lvalue.c:405]: lval_assign(): assignment failed at pos: (865,45-865,60)`
### RTPSniff prettyfied

`{`
`"timestamp": 1457210300,`
`"interval": 10,`
`"streams": 5,`
`"packets": 1444,`
`"lost": 4,`
`"late": 0,`
`"lost_perc": 0.277008,`
`"late_perc": 0.000000,`
`"out_of_seq": 0,`
`"delay_min": 0,`
`"delay_max": 102273,`
**`"delay_avg": 51136,`**
`"type": "rtp_stat"`
`}
### Statsmrtr (no errors observed)

Stats: { rcvd: 26, parsed: 13, sent: 13, err: 0 }

**Comment by lmangani** [comment]
Hi @ishmaelen 

"HOMER_CUSTOM_STATS"  is an example for advanced users to play with and share back ideas, it works when configured but still lacks flexibility in terms of dealing with the unexpected - consider it an experiment at this stage and feel free to send a PR or suggestions/fixes to improve it anytime - thanks!

**Comment by ishmaelen** [comment]
Hello @lmangani,

I appreciate that fact but I believe the examples existing in config should be valid or removed.

I am not sure but that error above seems to be something like delay_avg not being reflected in Kamailio config but being spit out by rtpsniff.

This would attract users to actually try their own implementations and would make Homer more attractive for people who are just testing to see what it can do.

Thanks for all your efforts!

**Comment by adubovikov** [comment]
the error in the syslog's log has nothing to do to "delay_avg". In the example the index has  jumped over 2, but this give you only notification error and stats should be inserted into DB anyway.

https://github.com/sipcapture/homer/wiki/Example:-CustomStats/_compare/b35d1fc6009fd2e9a5b0c3e402aa313ec8a55af2...5ae6504bf4b1c37a810242bc32a0daedc95f3a27
