### ISSUE TITLE
rotate script issue

### ISSUE THREAD

**Issue by oliverpena** [sipcapture/homer-api#77]
Hi,

I'm setting the Homer everythings looks, the DB looks good, the Web configs Looks good, but im having problems with the rotate scripts, im getting:

DBD::mysql::db do failed: Invalid default value for 'to_date' at ./homer_mysql_partrotate_unixtimestamp.pl line 160.
Failed to execute query [Invalid default value for 'to_date'] with error: DBD::mysql::db do failed: Invalid default value for 'to_date' at ./homer_mysql_partrotate_unixtimestamp.pl line 160.
Failed to execute query [Invalid default value for 'to_date'] with error: DBD::mysql::db do failed: Invalid default value for 'to_date' at ./homer_mysql_partrotate_unixtimestamp.pl line 160.
Failed to execute query [Invalid default value for 'to_date'] with error: DBD::mysql::db do failed: Invalid default value for 'to_date' at ./homer_mysql_partrotate_unixtimestamp.pl line 160.
Failed to execute query [Invalid default value for 'to_date'] with error: DBD::mysql::db do failed: Invalid default value for 'to_date' at ./homer_mysql_partrotate_unixtimestamp.pl line 160.

Everytime i run the homer_rotate script.

Please advice if you have some time.

Regards,

**Comment by adubovikov** [comment]
what version of Mysql you have ?

**Comment by adubovikov** [comment]
also please provide:

show create table homer_statistics.stats_data;

**Comment by oliverpena** [comment]
The MySQL version 
Server version: 5.7.11 MySQL Community Server

This is the output of "show create table stats_data;":
mysql> show create table stats_data;
+------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Table      | Create Table                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       |
+------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| stats_data | CREATE TABLE `stats_data` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `from_date` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `to_date` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `type` varchar(50) NOT NULL DEFAULT '',
  `total` int(20) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`,`from_date`),
  UNIQUE KEY `datemethod` (`from_date`,`to_date`,`type`),
  KEY `from_date` (`from_date`),
  KEY `to_date` (`to_date`),
  KEY `method` (`type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=COMPRESSED KEY_BLOCK_SIZE=8
/*!50100 PARTITION BY RANGE ( UNIX_TIMESTAMP(`from_date`))
(PARTITION pmax VALUES LESS THAN MAXVALUE ENGINE = InnoDB) */ |
+------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)

**Comment by adubovikov** [comment]
disable NO_ZERO_DATE in your mysql

http://dev.mysql.com/doc/refman/5.7/en/sql-mode.html#sqlmode_no_zero_date

or drop default '0000-00-00'

**Comment by oliverpena** [comment]
Thanks for the tip, it worked like charm now.
