### ISSUE TITLE
Login Error

### ISSUE THREAD

**Issue by oliverpena** [sipcapture/homer-api#78]
Hello,

I'm having problems with the login, im getting the error:

[Tue Apr 05 17:18:46 2016] [error] [client 192.168.81.79] File does not exist: /var/www/html/webhomer/api/v1, referer: http://192.168.81.146/

Here's my setup:
Mysql Version: Server version: 5.7.11 MySQL Community Server
PHP version: 5.5.33 (php55w-mysql package installed)
Apache Version: 2.2
OS: CentOS 6.7

Vhost Config httpd.conf:

<IfModule !mod_rewrite.c>
LoadModule rewrite_module modules/mod_rewrite.so
</IfModule>

<VirtualHost *:80>
        ServerAdmin root@localhost
        ServerName  XX.XX.XX.XX
        # Indexes + Directory Root.
        DirectoryIndex index.php index.html index.htm
        DocumentRoot /var/www/html/webhomer/

```
    <Directory /var/www/html/webhomer/>
        Options Indexes FollowSymLinks MultiViews
        AllowOverride all
        Order allow,deny
        allow from all
    </Directory>

    # CGI Directory
    ScriptAlias /cgi-bin/ /var/www/html/cgi-bin/
    <Location "/var/www/html/cgi-bin">
        Options +ExecCGI -MultiViews
        Order allow,deny
        Allow from all
    </Location>
 <Directory "/var/www/html/webhomer/api">
            Options Indexes FollowSymLinks MultiViews
            AllowOverride all
            RewriteEngine On
           Order allow,deny
            allow from all
    </Directory>

    # Logfiles
    ErrorLog  /var/log/httpd/sipcapture-error.log
    CustomLog /var/log/httpd/sipcapture-access.log combined
```

</VirtualHost>

**Comment by lmangani** [comment]
The configuration blocks seems possibly malformed or possibly its a partial paste. Could you post the full `<VirtualHost *:80>` block?

**Comment by oliverpena** [comment]
Hello, 

I've switch to nginx and im getting the same error. 

php-fpm is up and running. 
nginx group/user setup on the /var/www/html/webhomer directory, permissions looks good.

nginx default.conf file:
server {

```
    listen 80;

    root /var/www/html/webhomer;
    index index.html index.htm;

    # Make site accessible from http://localhost/
    server_name 192.168.81.146;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /api {
        include fastcgi_params;
        # NOTE: You should have "cgi.fix_pathinfo = 0;" in php.ini
        include fastcgi_params;
        fastcgi_pass 127.0.0.1:9001;
        # fastcgi_pass unix:/var/run/php5-fpm.sock;
        fastcgi_intercept_errors on;
        fastcgi_param  SCRIPT_FILENAME $document_root/api/index.php;
    }
```

}

Im using the homer5.php-fpm example file as my /etc/php-fpm.d/www.conf file

**Comment by lmangani** [comment]
Assuming the UI + UI/API are in place, try swapping to fastcgi_pass

```
        # fastcgi_pass 127.0.0.1:9001;
        fastcgi_pass unix:/var/run/php5-fpm.sock;
```

You can also check out the [bash installer](https://github.com/sipcapture/homer-installer) and check the code for any hints as of what might be missed in your setup.

**Comment by lmangani** [comment]
Please re-open if needed
