### ISSUE TITLE
sip search results

### ISSUE THREAD

**Issue by pinchasMT** [sipcapture/homer-api#79]
Is it possible to change sip search results columns (i would like to add cseq)
there are 3 custom columns (F1 F2 F3) in ui and in DB, how can i utilize these fields (example)

**Comment by lmangani** [comment]
Hi @pinchasMT I am not sure I understand the request, feel free to play around with the results table and send a PR if you wish. The extra fields are reserved for future dynamic allocation of fields or generated ones, not actively used yet.

**Comment by pinchasMT** [comment]
i would like to display cseq column in search results

**Comment by remi-blondel** [comment]
If people are still ending up in this topic, here is the solution:

You can go in /var/www/html/homer/js/modules/pages/controllers/resultCtrl.js and just add a line in "columnDefs" scope:

e.i. {field: 'cseq', displayName: 'cseq', visible: true},

**Comment by lmangani** [comment]
Thanks! Feel free to add this to the wiki for others to find, or PR if you think its critical. Thanks!

**Comment by remi-blondel** [comment]
I think the best place to add it would be there : https://github.com/sipcapture/homer/wiki/Using-Homer-5#grid-options but I don't have the permission to do that.

**Comment by lmangani** [comment]
@remi-blondel please try again :) thanks in advance!

**Comment by remi-blondel** [comment]
Done ! Let me know if I forgot something :)
