### ISSUE TITLE
mysql schema_statistic.sql: Invalid default value for 'to_date'

### ISSUE THREAD

**Issue by rayjanoka** [sipcapture/homer-api#80]
Hi Homer Team,

 I was building a server from scratch today and it failed when I was loading the schema_statistic.sql file.

[root@ip-10-81-89-89 homer-git]# mysql -u "root" -p"xxxxx" homer_statistic < homer-api/sql/schema_statistic.sql
ERROR 1067 (42000) at line 76: Invalid default value for 'to_date'

[root@ip-10-81-89-89 homer-git]# mysql --version
mysql  Ver 14.14 Distrib 5.6.30, for Linux (x86_64) using  EditLine wrapper

The problem seems to be related to this recent change 497da4d30571df272fca3b17a4f180a468913fab

**Comment by adubovikov** [comment]
thanks for bug report. 

https://github.com/sipcapture/homer-api/commit/51bce006fc16ddcf28dfda1fea16add74137fc97

**Comment by Pechenn** [comment]
Thats becose your system runs in another timezone than UTC.
`SELECT FROM_UNIXTIME(1);`
I juts change default to_date to '1970-01-01 03:00:01' to solve this problem on my system.
