### ISSUE TITLE
Kamailio configs and startup scripts/modules as an additional project/package

### ISSUE THREAD

**Issue by kvishnivetsky** [sipcapture/homer-api#9]
Hi, Guys.
As we can see, kamailio may be installed with default layout, but binary may be started as different services with different configuration.
So my suggestion is to add a package, which will contain:
1. kamailio configuration in /etc/kamailio/kamailio-sipcapture.cfg
2. statrtup defaults for kamailio in (for RHEL and forks):/etc/sysconfig/sipcapture (pidfile,lockfile,cfgfile parameters)
3. startup script for kamailio in (for RHEL6 and forks):/etc/init.d/sipcapture, startup module (for RHEL7 and forks):/usr/lib/systemd/system/sipcapture.service
4. dependencies on all needed kamilio packages

This will allow us to run kamailio as a separate service and do not make "manual configuration". I think those technics are very usefull for automated/mass deployment.

**Comment by kvishnivetsky** [comment]
Already done in homer-api package.
Issue may be closed.

**Comment by lmangani** [comment]
Thanks Konstantin!
