### ISSUE TITLE
Homer never stores dashboards to DB

### ISSUE THREAD

**Issue by foxx** [sipcapture/homer-api#90]
Inside `preferences.php` you have;

```
define('DASHBOARD_STORE','db');
define('DASHBOARD_PARAM', ROOT.'/store/dashboard');
```

However searching through the code shows that `DASHBOARD_STORE` is never checked for `db`, and always goes to disk.

This configurable should either be dropped from default config, or support added into the code.

**Comment by adubovikov** [comment]
http://install.sipcapture.io/
