### ISSUE TITLE
Empty Session Duration in Call Flow/QoS Result Dialog

### ISSUE THREAD

**Issue by benhelitel** [sipcapture/homer-api#97]
After a successful Homer install we noticed the Call-Flow/QoS dialog was showing a zero-length session duration for all calls.  Additionally, the SDP Session data was not present on the QoS tab.

After sifting through the code it appears that part of the query engine ($layerHelper) was targeting a non-existent table on the back end in api/RestApi/Report.php.  This seems to be due to an empty field assignment at Report.php:1147.

The $layerHelper['table']['type'] field should be set to 'call' for the query engine to hit the right table, but the $query_type variable being used for the assignment is empty.

We've temporarily hard-coded that line to 'call' and we are now seeing the correct call lengths displayed on the Call-Flow/QoS dialogs.  Additionally, SDP Session data is now showing correctly on the QoS tab as well.

i.e.  Replacing the following line:

``` php
        $layerHelper['table']['type'] = $query_type;
```

with the following:

``` php
        $layerHelper['table']['type'] = 'call';
```

has resolved the issue for us.

**Comment by adubovikov** [comment]
https://github.com/sipcapture/homer-api/commit/d926fbb36433e9b9ff320cf591bd20b8afef57c3

thank you!
